force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/cpm__Installment__c.object-meta.xml
<CustomObject>
    <description>Installments are the result of a Recurring Payment. Installments track the status of a invoice or a direct debit transaction.</description>
    <label>Installment</label>
    <nameField>
        <displayFormat>INST-{00000000}</displayFormat>
        <label>Installment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Account__c.field-meta.xml
<CustomField>
    <fullName>cpm__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The debitor, copied from Recurring Payment</description>
    <inlineHelpText>The debitor, copied from Recurring Payment</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/cpm__Contact__c.field-meta.xml
<CustomField>
    <fullName>cpm__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The debitor</description>
    <inlineHelpText>The debitor</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cpm__Installment__c/fields/fdff__GiftTransaction__c.field-meta.xml
<CustomField>
    <fullName>fdff__GiftTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift Transaction</label>
    <referenceTo>GiftTransaction</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Codes__c/Finance_Codes__c.object-meta.xml
<CustomObject>
    <label>Finance Code</label>
    <nameField>
        <label>Finance Codes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Codes__c/fields/PCode__c.field-meta.xml
<CustomField>
    <fullName>PCode__c</fullName>
    <label>PCode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Exclude_from_Findock_Gift_Aid_Processing__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Findock_Gift_Aid_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox ensures that related instalments auto created by Findock for Gift Aid Transactions are not eligible for Gift Aid</description>
    <inlineHelpText>Excludes related instalments from Gift Aid claims</inlineHelpText>
    <label>Exclude from Findock Gift Aid Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Finance_Code__c.field-meta.xml
<CustomField>
    <fullName>Finance_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Code</label>
    <referenceTo>Finance_Codes__c</referenceTo>
    <relationshipLabel>Gift Transactions</relationshipLabel>
    <relationshipName>Gift_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/recordTypes/Receivable.recordType-meta.xml
<RecordType>
    <fullName>Receivable</fullName>
    <active>true</active>
    <label>Receivable</label>
</RecordType>

force-app/main/default/objects/KillSwitch__c/KillSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>KillSwitch</label>
</CustomObject>

force-app/main/default/objects/KillSwitch__c/fields/Val_Instalment__c.field-meta.xml
<CustomField>
    <fullName>Val_Instalment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Val - Instalment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>Record and view data for people</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/AccountStatusGiftTestClass.cls
@IsTest 
    public class AccountStatusGiftTestClass{
    
    @TestSetup
        static void makeData() {
        
            Id personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
            
            Account accBefore = New Account(
               FirstName='James',
               LastName='Test Person', 
               Status__c='Existing',
               RecordTypeId=personAccountRecordTypeId
            );
            System.debug('Status Before Gift: ' + accBefore.Status__c + ' ,Last Name ' + accBefore.LastName + ' Person Account  ' + accBefore.IsPersonAccount + ' Record Type ' + accBefore.RecordTypeId);
            
            // Insert Account
            insert accBefore; 
            
            Account acc = [SELECT Id, PersonContactId FROM Account WHERE Id = :accBefore.Id];        
            Contact con = [SELECT Id, Name FROM Contact WHERE AccountId = :accBefore.Id];
            System.debug('Contact: ' + con);
            System.debug('Account: ' + accBefore.Id);   
            System.debug('PersonContactId: ' + acc.PersonContactId);    
            
            
            Finance_Codes__c finBefore = New Finance_Codes__c(
               Name='James Finance',
               PCode__c='666'
            );
            
            insert finBefore;
            
        //    cpm__GT_Installment_Field_Mapping__c CS = new cpm__GT_Installment_Field_Mapping__c (
         //   fdff__Gift_Transaction_Field__C ='DonorID', 
          //  fdff__Installment_Field__C='cpm__Account__C'
          //  );
            
        //    insert CS;
        
        Killswitch__c killSwitchSetting = new Killswitch__C(
        Val_Instalment__c = true
        );
        insert killSwitchSetting;
            
            
            Id GiftRecordTypeID = Schema.SObjectType.GiftTransaction.getRecordTypeInfosByDeveloperName().get('Receivable').getRecordTypeId();
               
            GiftTransaction gift = new GiftTransaction(
               Name='James Transaction', 
               Status='Paid',
               Finance_Code__c=finBefore.Id, 
               OriginalAmount=5000, 
               TransactionDate=Date.today(),
               DonorId=accBefore.Id, 
               PaymentMethod='PayPal', 
               GiftType='Individual',
               RecordTypeId=GiftRecordTypeID,
               Exclude_from_Findock_Gift_Aid_Processing__c=True
            );
            
            System.debug('Gift Transaction: ' + gift);
            
            // Insert Gift Transaction        
            insert gift;
             
            //   cpm__Installment__c install = new cpm__Installment__c(
            //  cpm__Account__c=accBefore.Id,
            //  cpm__Contact__c=accBefore.PersonContactId,
            //  fdff__GiftTransaction__c=gift.Id
            //     );
            
            //    System.debug('Donor: ' + install.cpm__Account__c);
            
            //insert install;
            
    }
    
        @IsTest
    
            static void validateAccountStatusBasedOnGiftTransaction() { 
            Test.startTest();
            
            AccountStatusBasedOnGiftTransaction batch = new AccountStatusBasedOnGiftTransaction();
            DataBase.executeBatch(batch);
            
            Test.stopTest();
            
            // Retrieve Donor
            
            Account accAfter = [SELECT Status__c FROM Account LIMIT 1];
            System.debug('Status Of Account: ' + accAfter.Status__c);
            
            // Test that the trigger correctly updated the status
            Assert.areEqual('New', accAfter.Status__c,'Account Status should be set to New.');
        }
    }