force-app/main/default/objects/Contact/fields/sj_FileSource__c.field-meta.xml
<CustomField>
    <fullName>sj_FileSource__c</fullName>
    <description>Data Migration</description>
    <label>sj_FileSource__c</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPointTypeConsent/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contact Point Type Consents</relationshipLabel>
    <relationshipName>Contact_Point_Type_Consents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPointTypeConsent/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>The outbound communication channel the supporter has agreed to.</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPointTypeConsent/fields/Consent_Capture_Source__c.field-meta.xml
<CustomField>
    <fullName>Consent_Capture_Source__c</fullName>
    <label>Consent Capture Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <label>Direct Email</label>
            </value>
            <value>
                <fullName>Phone</fullName>
                <label>Direct Phone</label>
            </value>
            <value>
                <fullName>Donations on website</fullName>
            </value>
            <value>
                <fullName>POD portal</fullName>
            </value>
            <value>
                <fullName>Event ticket sales</fullName>
            </value>
            <value>
                <fullName>Referral Sign Ups</fullName>
            </value>
            <value>
                <fullName>Campaign actions</fullName>
            </value>
            <value>
                <fullName>Global Opt Out</fullName>
            </value>
            <value>
                <fullName>CAF GAYE</fullName>
            </value>
            <value>
                <fullName>CAF Online/Direct</fullName>
            </value>
            <value>
                <fullName>Charitable Giving</fullName>
            </value>
            <value>
                <fullName>Work for Good</fullName>
            </value>
            <value>
                <fullName>Benevity</fullName>
            </value>
            <value>
                <fullName>Just Giving</fullName>
                <label>JustGiving</label>
            </value>
            <value>
                <fullName>Charities Trust (Payroll)</fullName>
            </value>
            <value>
                <fullName>Enthuse</fullName>
            </value>
            <value>
                <fullName>Donr</fullName>
            </value>
            <value>
                <fullName>Hands on Payroll Giving</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Mailing Preference Service</fullName>
            </value>
            <value>
                <fullName>FinDock Giving Page</fullName>
            </value>
            <value>
                <fullName>Fundraising Preference Service</fullName>
            </value>
            <value>
                <fullName>Give as you Live</fullName>
            </value>
            <value>
                <fullName>Give Star</fullName>
            </value>
            <value>
                <fullName>Mailing House Suppression</fullName>
            </value>
            <value>
                <fullName>Meta</fullName>
            </value>
            <value>
                <fullName>Return Fundraising</fullName>
            </value>
            <value>
                <fullName>The Big Give</fullName>
            </value>
            <value>
                <fullName>Upward Comms</fullName>
            </value>
            <value>
                <fullName>Virgin Money</fullName>
            </value>
            <value>
                <fullName>Social Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPointTypeConsent/fields/Consent_Statement__c.field-meta.xml
<CustomField>
    <fullName>Consent_Statement__c</fullName>
    <label>Consent Statement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAFGAYE1</fullName>
                <label>Email sent by CAF: at the bottom of the page, it asks whether the donor wishes to share their details with the charity.  If they click on the box, the donations they make will be sent to the charity anonymously.</label>
            </value>
            <value>
                <fullName>CAFOnline1</fullName>
                <label>If you do not tick this box, your personal contact information and donation details will be sent to the organisation you are donating to. It may be stored and used by them to get in touch with you.</label>
            </value>
            <value>
                <fullName>CharitableGiving1</fullName>
                <label>If you check any of the boxes below the information you provide will be shared with the charity. Charitable Giving is not responsible for how your charities use this information. If you do not check any of the boxes, then your details won&apos;t shared.</label>
            </value>
            <value>
                <fullName>WorkForGood1</fullName>
                <label>If &apos;yes&apos;, Work for Good will share your name and email address with the charity so they can keep in touch about the impact of your fundriasing and other ways to support them. You can update your preferences directly with the charity at any time.</label>
            </value>
            <value>
                <fullName>Benevity1</fullName>
                <label>You may choose to send a message to this charity along with your gift. Please note that specific instructions on the use of these funds are not binding for the recipient. Your name will be included with any optional comments you choose to add.</label>
            </value>
            <value>
                <fullName>JustGiving1</fullName>
                <label>I’m happy for FareShare to keep in touch with me by email about the impact of my donation and other ways I can support them in the future. I understand that JustGiving will need to pass my information to them in order for them to do so.</label>
            </value>
            <value>
                <fullName>CharitiesTrust1</fullName>
                <label>The charity is only permitted to contact you if you give them specific consent. To opt in to receive information, please indicate your contact preferences by ticking the relevant boxes. No boxes ticked means that no contact info is passed to the charity.</label>
            </value>
            <value>
                <fullName>Enthuse1</fullName>
                <label>We&apos;d love to keep you up to date on FareShare&apos;s work including fundraising updates. Please let us know if it&apos;s okay to contact you. We&apos;ll never share your data with third parties for marketing purposes</label>
            </value>
            <value>
                <fullName>DONR1</fullName>
                <label>Please email me updated on how my donation is helping and ways to get involved. I would like to hear from: [Box for FareShare]</label>
            </value>
            <value>
                <fullName>HandsOnPayrollGiving1</fullName>
                <label>Opting in to receive communications means you can see how your charity use your gift. Please indicate which channels your charity may use. If you select no contact then you won&apos;t hear from your charity. We will never share your details without consent.</label>
            </value>
            <value>
                <fullName>SocialSync1</fullName>
                <label>We would love to talk to you in the future about our work and the different opportunities to support FareShare such as fundraising, volunteering, donating, and campaigning. You can update your contact preferences at any time by calling us or emailing</label>
            </value>
            <value>
                <fullName>BigGive1</fullName>
                <label>Would you like to receive emails from FareShare? Yes I&apos;m happy to recieve emails from FareShare. Would you like to receive emails from The Big Give? Yes I would like to receive emails from The Big Give.</label>
            </value>
            <value>
                <fullName>PayrollGiA1</fullName>
                <label>By using the PGiA website or submitting data to PGiA, each user consents to the use of a user personal data in the manner set out in the PGiA privacy statement.</label>
            </value>
            <value>
                <fullName>CommittedGiving1</fullName>
                <label>We may send you information about products and services of ours that we believe may be of interest to you. You have the right at any time to stop us contacting you. If you no longer wish to be contacted for marketing purposes, please contact us.</label>
            </value>
            <value>
                <fullName>Return1</fullName>
                <label>We may send you information about products and services of ours that we believe may be of interest to you. You have the right at any time to stop us contacting you. If you no longer wish to be contacted for marketing purposes, please contact us</label>
            </value>
            <value>
                <fullName>VirginMoney1</fullName>
                <label>We commit to never using personal details for marketing purposes if customers tell us not to, only sending marketing info in the format they’ve agreed (email, post, SMS &amp; telephone), not passing customer data to a third party for marketing reasons.</label>
            </value>
            <value>
                <fullName>GiveStar1</fullName>
                <label>I am happy for FareShare to email me using the email address I have provided.</label>
            </value>
            <value>
                <fullName>UpwardComms1</fullName>
                <label>Please let us know if you are happy for FareShare to keep in touch with you about the impact of my donation and other ways you can support them in the future</label>
            </value>
            <value>
                <fullName>We would love to talk to you in the future about our work and the different opportunities to support FS and get involved. For full details of how we use your data, please read our Privacy Policy. Please let us know how you&apos;re happy to hear from FS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPointTypeConsent/fields/Legal_Basis__c.field-meta.xml
<CustomField>
    <fullName>Legal_Basis__c</fullName>
    <description>Consent: The individual has given their permission, for a specific purpose to contact them via a particular channel.

Legitimate Interests: Because of interest shown in the past we believe the supporter will be happy to hear from us (Note: only applies to Post and Phone).

Contract: Because supporter has directly signed up for information.</description>
    <inlineHelpText>Consent: The individual has given their permission, for a specific purpose to contact them via a particular channel.

Legitimate Interests: Because of interest shown in the past we believe the supporter will be happy to hear from us (Note: only applies to Post and Phone).

Contract: Because supporter has directly signed up for information.</inlineHelpText>
    <label>Legal Basis</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consent</fullName>
                <default>true</default>
                <label>Consent</label>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Legitimate Interest</fullName>
                <isActive>false</isActive>
                <label>Legitimate Interest</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPointTypeConsent/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contact Point Type Consents</relationshipLabel>
    <relationshipName>Contact_Point_Type_Consents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Individual/fields/sj_FileSource__c.field-meta.xml
<CustomField>
    <fullName>sj_FileSource__c</fullName>
    <description>Data Migration</description>
    <label>sj_FileSource__c</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataCloudContactPointTypeConsent.cls
/**
 * @description Used to upsert ContactPointTypeConsent records 
 *
 * @author Solution Junkies
 *
 * @date 2024
 */
public class DataCloudContactPointTypeConsent {
    /**
     * @description Upserts ContactPointTypeConsen records when platform event triggered flow is fired
     */
    @InvocableMethod(label='Upsert Consent Records' description='Upserts Consent records')
    public static void upsertConsentRecord(List<Request> requestList) { 
        System.debug(requestList);
        
        String dataSource = requestList[0].data_source;
        List<ContactPointTypeConsent> consentsToUpsert = new List<ContactPointTypeConsent>();
        Map<Id, ContactPointTypeConsent> consentsToUpsertMap = new Map<Id, ContactPointTypeConsent>();
        Map<String, String> accToIndvMap = new Map<String, String>(); 
        List<String> listOfPersonAccIds = new List<String>();
        
        // Collate list of Person Account ids
        for (Request req : requestList) {
            listOfPersonAccIds.add(req.personaccount_id);
        }
        
        // Find Individual ids from Person Account ids
        List<Contact> indvList = [SELECT Id, IndividualId, AccountId FROM Contact WHERE AccountId IN : listOfPersonAccIds];
        for (Contact con : indvList) {
            accToIndvMap.put(con.AccountId, con.IndividualId);
        }
        
        // Get DataUsePurpose id
        String marketingPurposeId = [SELECT Id, Name FROM DataUsePurpose WHERE Name = 'Marketing'].size() == 1 ? [SELECT Id, Name FROM DataUsePurpose WHERE Name = 'Marketing'].Id : null; 
        String emailMassParticipationPurposeId = [SELECT Id, Name FROM DataUsePurpose WHERE Name = 'Mass Event Participation'].size() == 1 ? [SELECT Id, Name FROM DataUsePurpose WHERE Name = 'Mass Event Participation'].Id : null; 
        
        // Get existing consents
        List<ContactPointTypeConsent> existingConsents = [SELECT Id, Person_Account__c, Channel__c, PrivacyConsentStatus, DataUsePurposeId
                                                         FROM ContactPointTypeConsent WHERE Person_Account__c IN : listOfPersonAccIds];
        
        // Consent channel maps
        Map<String, ContactPointTypeConsent> consentEmailMap = new Map<String, ContactPointTypeConsent>();
        Map<String, ContactPointTypeConsent> consentPhoneMap = new Map<String, ContactPointTypeConsent>();
        Map<String, ContactPointTypeConsent> consentPostMap = new Map<String, ContactPointTypeConsent>();
        Map<String, ContactPointTypeConsent> consentSmsMap = new Map<String, ContactPointTypeConsent>();
        Map<String, ContactPointTypeConsent> consentWhatsappMap = new Map<String, ContactPointTypeConsent>();
        Map<String, ContactPointTypeConsent> consentMassParticipationMap = new Map<String, ContactPointTypeConsent>();
        
        for (ContactPointTypeConsent consent : existingConsents) {
            if (consent.Channel__c.toLowerCase() == 'email' && consent.DataUsePurposeId == marketingPurposeId) {
                consentEmailMap.put(consent.Person_Account__c, consent);
            } 
            if (consent.Channel__c.toLowerCase() == 'phone') {
                consentPhoneMap.put(consent.Person_Account__c, consent);
            }
            if (consent.Channel__c.toLowerCase() == 'post') {
                consentPostMap.put(consent.Person_Account__c, consent);
            }     
            if (consent.Channel__c.toLowerCase() == 'sms') {
                consentSmsMap.put(consent.Person_Account__c, consent);
            }     
            if (consent.Channel__c.toLowerCase() == 'whatsapp') {
                consentWhatsappMap.put(consent.Person_Account__c, consent);
            }   
            if (consent.Channel__c.toLowerCase() == 'email' && consent.DataUsePurposeId == emailMassParticipationPurposeId) {
                consentMassParticipationMap.put(consent.Person_Account__c, consent);
            } 
        }
        
        Map<String, String> consentOptInOutMap = new Map<String, String>();
        consentOptInOutMap.put('TRUE', 'OptIn');
        consentOptInOutMap.put('FALSE', 'OptOut');
        
        Map<String, String> consentStatementMap = new Map<String, String>();
        consentStatementMap.put('Donr', 'DONR1');
        consentStatementMap.put('Social Sync Registration', 'SocialSync1');
        consentStatementMap.put('Social Sync Transaction', 'SocialSync1');
        consentStatementMap.put('UpwardComms', 'UpwardComms1');    
        consentStatementMap.put('Return', 'Return1'); 
        
        Map<String, String> consentCaptureSourceMap = new Map<String, String>();
        consentCaptureSourceMap.put('Donr', 'Donr');
        consentCaptureSourceMap.put('Social Sync Registration', 'Social Sync');
        consentCaptureSourceMap.put('Social Sync Transaction', 'Social Sync');
        consentCaptureSourceMap.put('UpwardComms', 'Upward Comms');    
        consentCaptureSourceMap.put('Return', '	Return Fundraising');         
                
        for (Request req : requestList) {   
            if (req.personaccount_id != null && req.personaccount_id != '') {      
                // Email Consent
                if (req.email_consent != null && req.email_consent != '') {
                    // If Consent record does not exist but Consent preference has come through, create record
                    if (consentEmailMap.get(req.personaccount_id) == null) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Name = 'Email - Marketing';
                        consentRecord.Channel__c = 'Email';
                        consentRecord.DataUsePurposeId = marketingPurposeId;
                        consentRecord.Legal_Basis__c = 'Consent';
                        consentRecord.Person_Account__c = req.personaccount_id;
                        consentRecord.PartyId = accToIndvMap.get(req.personaccount_id);
                        consentRecord.PrivacyConsentStatus = req.email_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.email_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentRecord.sj_FileSource__c = 'Data Cloud - ' + dataSource;
                        consentsToUpsert.add(consentRecord); 
                    }
                    
                    // If Consent record does exist but Consent preference is different, update record            
                    else if (consentEmailMap.get(req.personaccount_id) != null && consentEmailMap.get(req.personaccount_id).PrivacyConsentStatus != consentOptInOutMap.get(req.email_consent)) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Id = consentEmailMap.get(req.personaccount_id).Id;
                        consentRecord.PrivacyConsentStatus = req.email_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.email_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';    
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentsToUpsertMap.put(consentRecord.Id, consentRecord);
                    }                  
                }
             
                // Phone Consent
                if (req.phone_consent != null && req.phone_consent != '') {
                    // If Consent record does not exist but Consent preference has come through, create record
                    if (consentPhoneMap.get(req.personaccount_id) == null) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Name = 'Phone - Marketing';
                        consentRecord.Channel__c = 'Phone';
                        consentRecord.DataUsePurposeId = marketingPurposeId;
                        consentRecord.Legal_Basis__c = 'Consent';
                        consentRecord.Person_Account__c = req.personaccount_id;
                        consentRecord.PartyId = accToIndvMap.get(req.personaccount_id);
                        consentRecord.PrivacyConsentStatus = req.phone_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.phone_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentRecord.sj_FileSource__c = 'Data Cloud - ' + dataSource;
                        consentsToUpsert.add(consentRecord);                 
                    }
                    
                    // If Consent record does exist but Consent preference is different, update record            
                    else if (consentPhoneMap.get(req.personaccount_id) != null && consentPhoneMap.get(req.personaccount_id).PrivacyConsentStatus != consentOptInOutMap.get(req.phone_consent)) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Id = consentPhoneMap.get(req.personaccount_id).Id;
                        consentRecord.PrivacyConsentStatus = req.phone_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.phone_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';  
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentsToUpsertMap.put(consentRecord.Id, consentRecord);
                    }                  
                }
                
                // Post Consent
                if (req.post_consent != null && req.post_consent != '') {
                    // If Consent record does not exist but Consent preference has come through, create record
                    if (consentPostMap.get(req.personaccount_id) == null) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Name = 'Post - Marketing';
                        consentRecord.Channel__c = 'Post';
                        consentRecord.DataUsePurposeId = marketingPurposeId;
                        consentRecord.Legal_Basis__c = 'Consent';
                        consentRecord.Person_Account__c = req.personaccount_id;
                        consentRecord.PartyId = accToIndvMap.get(req.personaccount_id);
                        consentRecord.PrivacyConsentStatus = req.post_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.post_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentRecord.sj_FileSource__c = 'Data Cloud - ' + dataSource;
                        consentsToUpsert.add(consentRecord);     
                    }
                    
                    // If Consent record does exist but Consent preference is different, update record            
                    else if (consentPostMap.get(req.personaccount_id) != null && consentPostMap.get(req.personaccount_id).PrivacyConsentStatus != consentOptInOutMap.get(req.post_consent)) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Id = consentPostMap.get(req.personaccount_id).Id;
                        consentRecord.PrivacyConsentStatus = req.post_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.post_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';  
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentsToUpsertMap.put(consentRecord.Id, consentRecord);
                    }                  
                }
                
                // SMS Consent
                if (req.sms_consent != null && req.sms_consent != '') {
                    // If Consent record does not exist but Consent preference has come through, create record
                    if (consentSmsMap.get(req.personaccount_id) == null) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Name = 'SMS - Marketing';
                        consentRecord.Channel__c = 'SMS';
                        consentRecord.DataUsePurposeId = marketingPurposeId;
                        consentRecord.Legal_Basis__c = 'Consent';
                        consentRecord.Person_Account__c = req.personaccount_id;
                        consentRecord.PartyId = accToIndvMap.get(req.personaccount_id);
                        consentRecord.PrivacyConsentStatus = req.sms_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.sms_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentRecord.sj_FileSource__c = 'Data Cloud - ' + dataSource;
                        consentsToUpsert.add(consentRecord);     
                    }
                    
                    // If Consent record does exist but Consent preference is different, update record            
                    else if (consentSmsMap.get(req.personaccount_id) != null && consentSmsMap.get(req.personaccount_id).PrivacyConsentStatus != consentOptInOutMap.get(req.sms_consent)) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Id = consentSmsMap.get(req.personaccount_id).Id;
                        consentRecord.PrivacyConsentStatus = req.sms_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.sms_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentsToUpsertMap.put(consentRecord.Id, consentRecord);
                    }                  
                }
                
                // Whatsapp Consent
                if (req.whatsapp_consent != null && req.whatsapp_consent != '') {
                    // If Consent record does not exist but Consent preference has come through, create record
                    if (consentWhatsappMap.get(req.personaccount_id) == null) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Name = 'WhatsApp - Marketing';
                        consentRecord.Channel__c = 'Whatsapp';
                        consentRecord.DataUsePurposeId = marketingPurposeId;
                        consentRecord.Legal_Basis__c = 'Consent';
                        consentRecord.Person_Account__c = req.personaccount_id;
                        consentRecord.PartyId = accToIndvMap.get(req.personaccount_id);
                        consentRecord.PrivacyConsentStatus = req.whatsapp_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.whatsapp_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentRecord.sj_FileSource__c = 'Data Cloud - ' + dataSource;
                        consentsToUpsert.add(consentRecord);    
                    }
                    
                    // If Consent record does exist but Consent preference is different, update record            
                    else if (consentWhatsappMap.get(req.personaccount_id) != null && consentWhatsappMap.get(req.personaccount_id).PrivacyConsentStatus != consentOptInOutMap.get(req.whatsapp_consent)) {
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Id = consentWhatsappMap.get(req.personaccount_id).Id;
                        consentRecord.PrivacyConsentStatus = req.whatsapp_consent == 'TRUE' ? 'OptIn' : 'OptOut'; 
                        consentRecord.Consent_Statement__c = req.whatsapp_consent == 'TRUE' ? consentStatementMap.get(req.data_source) : '';
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentsToUpsertMap.put(consentRecord.Id, consentRecord);
                    }                  
                }
                
                // Social Sync Registration - Mass Participation Email Consent
                if (req.data_source == 'Social Sync Registration') {
                    // If Consent record does not exist, create additional Email Consent record
                    if (consentMassParticipationMap.get(req.personaccount_id) == null) { 
                        ContactPointTypeConsent consentRecord = new ContactPointTypeConsent();
                        consentRecord.Name = 'Email - Mass Participation';
                        consentRecord.Channel__c = 'Email';
                        consentRecord.DataUsePurposeId = emailMassParticipationPurposeId;
                        consentRecord.Legal_Basis__c = 'Consent';
                        consentRecord.Person_Account__c = req.personaccount_id;
                        consentRecord.Campaign__c = req.campaign_id;
                        consentRecord.PartyId = accToIndvMap.get(req.personaccount_id);
                        consentRecord.PrivacyConsentStatus = 'OptIn'; 
                        consentRecord.Consent_Statement__c = consentStatementMap.get(req.data_source);
                        consentRecord.Consent_Capture_Source__c = consentCaptureSourceMap.get(req.data_source);
                        consentRecord.sj_FileSource__c = 'Data Cloud - ' + dataSource;
                        consentsToUpsert.add(consentRecord);    
                    }               
                }
            }
        } 
            
        consentsToUpsert.addAll(consentsToUpsertMap.values());
        System.debug(consentsToUpsert.size());
        System.debug(consentsToUpsert);
        //Database.upsert(consentsToUpsert, false);   
        upsert consentsToUpsert;
    }
        
    public class Request {        
        @InvocableVariable
        public String email_consent;        
        
        @InvocableVariable
        public String phone_consent;    
        
        @InvocableVariable
        public String post_consent;        
        
        @InvocableVariable
        public String sms_consent;  
        
        @InvocableVariable
        public String whatsapp_consent;  
                
        @InvocableVariable
        public String personaccount_id;     
        
        @InvocableVariable
        public String campaign_id;     
        
        @InvocableVariable
        public String data_source;     
    }
}